# Site settings
name: Eshaan Dabasiya
title: Eshaan Dabasiya | Software Engineer
description: A systems-minded software engineer focused on architecting high-performance backends and contributing to the future of open source. 
url: https://eshaandabasiya.com/
baseurl: ""
email: eshaandabasiya@gmail.com
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://brittanychiang.com/resume.pdf
social:
  - title: email
    url: mailto:eshaandabasiya@gmail.com
  - title: instagram
    url: https://instagram.com/im3dabasia
  - title: WordPress
    url: https://profiles.wordpress.org/im3dabasia1/
  - title: github
    url: https://github.com/im3dabasia
  - title: linkedin
    url: https://www.linkedin.com/in/im3dabasia

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
